version: 0.2

phases:
  install:
    commands:
      - python3 -m pip install --upgrade pip
      - python3 -m pip install -r requirements.txt
  build:
    commands:
      - python3 -m mkdocs build
      
artifacts:
  type: zip
  files:
    - "**/*"
  base-directory: site